### ISSUE TITLE
technicolor/dwg855_authbypass.py  Generates False Positive 

### ISSUE THREAD

**Issue by omar-mohammad** [reverse-shell/routersploit#174]
Hi ,

This module shows that NETGEAR WNR1000v4 router is vulnerable , and this is a false positive 

Thanks

**Comment by fwkz** [comment]
@omar-mohammad Have you tried investigate why is that?

**Comment by omar-mohammad** [comment]
In scanner mode , it checks the logo and extract a specific string ("\x11\x44\x75\x63\x6b\x79\x00"  # Hex data of 0x11 + "Ducky" + 0x00 found on image "logo.jpg" )

url = sanitize_url("{}:{}/logo.jpg".format(self.target, self.port))


it looks, that logo is used by NETGEAR too,


when exploiting the bug

 it uses this path /goform/RgSecurity

            if response is None:
                print_error("Target did not answer request")
            elif response.status_code == 401:
                print_error("Target answered, denied access.")
            else:
                print_success("Credentials changed")


we have these conditions above , in my example the response is 404 Not Found, so it will print (Credentials changed )

I suggest to verify by another way instead of logo.jpg , even if there is no efficient way , in the exploit you should add more strict way when checking the response  , e.g. based on response length etc..

**Comment by 0BuRner** [comment]
Hi,

From my point of view, I think we should not verify the way you describe @omar-mohammad, it is too strict.
Sometimes, a vulnerability exists for a brand/model that is not known as vulnerable yet. If you block the process because of a too strict check() method, you can never discover new vulnerable model this way. It probably doesn't occur frequently, but I think it is worst to miss some vulnerable device than to have false-positive ones.

Nevertheless, I updated the script to manage 404 error because it should indeed not occur on vulnerable device.

**Comment by fwkz** [comment]
fixed in #180
