### ISSUE TITLE
Extracting password file

### ISSUE THREAD

**Issue by ScrimForever** [reverse-shell/routersploit#284]
Ever time like i try exploit my router, framework stop in this screen:

[http://tinypic.com/view.php?pic=33fb81l&s=9#.WXIvTSeQxpQ](url)

What i'm doing wrong. Device apear vulnerable

**Comment by 0BuRner** [comment]
Something is weird indeed. Two possible causes :

1. Bug in the exploit
2. This is a false positive and you firmware is not vulnerable (because of patched firmware)

Can you edit the following file and try again : routersploit/routersploit/modules/exploits/routers/multi/rom0.py

Replace 
`        fhandle.seek(fpos)
        while fpos < fend:
            if fend - fpos < amount:
                amount = fend - fpos
                chunk = fhandle.read(amount)
                fpos += len(chunk)`
With
`        fhandle.seek(fpos)
         chunk = fhandle.read(fend - fpos)
         fpos += len(chunk)`

Let me know if it works so I'll make a pull request =)

**Comment by ScrimForever** [comment]
So sorry, perfect, fine

**Comment by 0BuRner** [comment]
Sry but I dont hey it. 
Did you try to replace the code as said? Did it work?

**Comment by lucyoa** [comment]
Closing, seems like the similar issue to #285
