### ISSUE TITLE
Contribution : Module DLINK Hedwig Buffer Overflow to RCE

### ISSUE THREAD

**Issue by realoriginal** [reverse-shell/routersploit#317]
I've written a module that I wish to contribute to this project. Very much apologize if this is not the place to place it, just was unsure where and unable to find a place to submit

.

**Comment by jabedude** [comment]
@realoriginal thanks for the contribution.  In order to get this module into routersploit, please do the following:

1. Fork routersploit on github.
2. Place this code inside routersploit/routersploit/modules/exploits/routers/dlink/multi_hedwig_cgi_rce.py
3. Commit + push to your forked repo.
4. Open a pull request.

More info here: https://help.github.com/articles/creating-a-pull-request/
