### ISSUE TITLE
Request exploits for ZTE ZXHN F608

### ISSUE THREAD

**Issue by tuthieu** [reverse-shell/routersploit#339]
Hello,
Can you please add exploits for ZTE ZHN F608?
Routersploit show the router is only vulnerable with exploits/routers/zte/zxv10_rce
I successfully logged in router.But I cannot do anything in cmd.
[https://imgur.com/a/sjUN8](url)
Thank you so much!

PS:My ISP config the router to use only HTTPS(although browser keeps saying invalid certificate).When in browser,I can not access router via 192.168.1.1:443 but https://192.168.1.1 http://192.168.1.1 or 192.168.1.1:80 then the page redirect to https.
When I use routersploit,it only works when I set target https://192.168.1.1 and set port 443 which is opposite to browser.

**Comment by AlexHilgertBRA** [comment]
@tuthieu 
ZTE ZHN F608? Can't find anything about it.

On 'ZTE ZXV10 RCE' exploit, I think it may be a false positive that was fixed. Could you give a 'git pull' inside RouterSploit dir and check it again?

See ya.

**Comment by tuthieu** [comment]
@AlexHilgertBRA
Thank you for replying.
The device is now not vulnerable with any exploits.
How can I find an exploits?
I have two same device.One I know login and the other I don't know

**Comment by AlexHilgertBRA** [comment]
@tuthieu As I said, I didn't find any useful information about it, so I think the only way is whether you do it by yourself or "by hand". The real question is why you want to exploit it? You know, if the issue is just to login on it, you can bruteforce it, and if it is yours, you can just reset it.

The little I know about this device, is that default credentials is admin as user and serial number as password, so you get something this:

admin:ZTEGC???????

First two '??' seems to be a year, like 13, 14, 15, 16, etc.
Left five '??' seems to be a upper hex charset.

And finally, if it is yours, you can just see it on the back of your Router.

Cheers.

**Comment by tuthieu** [comment]
@AlexHilgertBRA ,I just want to find a way to exploit the router.
Thank you very much.
Your info is very helpful.

**Comment by AlexHilgertBRA** [comment]
@tuthieu You'd waste some years with this limitation I think. You'll get better with ftp or something else, which doesn't mean you won't waste a very very long time as well. You could access the router you have the pass through ssh and give a `cat /etc/passwd` to see if there are other default users and use it to login in the other router. You know, the possibilities are unlimited, the thing is that when we want to exploit something, we need to do a research about it, and have access to it, without it, we are with empty hands.

If there's ftp enabled or something else, you can use RouterSploit to bruteforce it, with `creds/ftp_bruteforce` for example. You just need to set the path of passwords to the extracted file ([ZTEGCYYHHHHH.zip](https://github.com/reverse-shell/routersploit/files/1484764/ZTEGCYYHHHHH.zip)).

**Comment by tuthieu** [comment]
@AlexHilgertBRA
Thank you for your suggest,but my ISP config the router to only accepts web access.

**Comment by AlexHilgertBRA** [comment]
@tuthieu No problem. It's not viable to bruteforce that keyspace with this limitation. See ya.
